"""empty message

Revision ID: 39dcc167073a
Revises: c759070d4a0b
Create Date: 2017-10-24 20:33:18.779689

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '39dcc167073a'
down_revision = 'c759070d4a0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question', 'content',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question', 'content',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
