"""empty message

Revision ID: d3b9fc0e5cdf
Revises: 9ff0d86b1b0a
Create Date: 2017-10-24 13:35:14.840494

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd3b9fc0e5cdf'
down_revision = '9ff0d86b1b0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question', 'content',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('question', 'title',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question', 'title',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('question', 'content',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
